name: PickupArrows
main: de.dustplanet.pickuparrows.PickupArrows
description: Allows you to pickup arrows
version: ${project.version}${build.number}
author: xGhOsTkiLLeRx
authors: [mushroomhostage]
website: https://dev.bukkit.org/projects/pickuparrows
commands:
  pickuparrows:
    description: Toggles whether arrows should be picked up
    aliases: [pa, arrow, arrows, pickuparrow]
permissions:
  pickuparrows.*:
    children:
      pickuparrows.allow.*: true
    default: op
  pickuparrows.allow.*:
    children:
        pickuparrows.allow.fire: true
        pickuparrows.allow.normal: true
        pickuparrows.allow.spectral: true
        pickuparrows.allow.tipped: true
    default: op
  pickuparrows.allow.fire:
    default: op
  pickuparrows.allow.normal:
    default: op
  pickuparrows.allow.spectral:
    default: op
  pickuparrows.allow.tipped:
    default: op
softdepend: [WorldGuard]
