name: Build the plugin

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java v21
      uses: actions/setup-java@v4.4.0
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Version information
      run: |
        java -version
        mvn --version

    - name: Build with Maven
      run: mvn -D"http.keepAlive=false" -D"maven.wagon.http.pool=false" -D"maven.wagon.httpconnectionManager.ttlSeconds=120" -B -V clean package
